services:
  app:
    build: .
    container_name: app_service
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:latest
    container_name: app_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: offeruser
      POSTGRES_PASSWORD: offerpass
      POSTGRES_DB: offerdb
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - pgdata:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    container_name: laravel_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:

volumes:
  pgdata:
